{
    'name': 'SOBTO - Personnalisation Facturation',
    'version': '18.0.1.23.0',
    'category': 'Accounting/Accounting',
    'summary': 'Personnalisation du module de facturation pour SOBTO',
    'author': 'SOBTO',
    # sale : champ sale_line_warn obligatoire sur product.template (données transport_products.xml)
    'depends': ['account', 'sale'],
    'post_init_hook': 'post_init_hook',
    'data': [
        'security/ir.model.access.csv',
        'data/transport_products.xml',
        'views/sobto_parcours_views.xml',
        'views/sobto_camion_views.xml',
        'views/res_partner_views.xml',
        'views/res_company_views.xml',
        'views/account_move_views.xml',
        'reports/report_invoice_sobto.xml',
        'reports/report_invoice_actions.xml',
        'reports/report_invoice_sobto_action.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
}
