{
    'name': 'SOBTO - Personnalisation Facturation',
    'version': '18.0.1.11.5',
    'category': 'Accounting/Accounting',
    'summary': 'Personnalisation du module de facturation pour SOBTO',
    'author': 'SOBTO',
    'depends': ['account'],
    'post_init_hook': 'post_init_hook',
    'data': [
        'security/ir.model.access.csv',
        'views/sobto_parcours_views.xml',
        'views/res_partner_views.xml',
        'views/res_company_views.xml',
        'views/account_move_views.xml',
        'reports/report_invoice_sobto.xml',
        'reports/report_invoice_actions.xml',
        'reports/report_invoice_sobto_action.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
}
